iocc:
  address: 0x20
  verbose: true
  i2c_speed_hz: 400000 #in Hz
  reset_on_open: false
  timeout: 10 # in milliseconds

mitac:
  address: 0x20
  verbose: false
  i2c_speed_hz: 400000 #in Hz
  reset_on_open: false
  timeout: 10 # in milliseconds
  ignition:
    port: portb
    pin: pin1
    direction: output
    on_is: 0
